// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLLv54m6zoTeQYhvnp-6dMIwZWRBFmTN0',
    appId: '1:69817314886:web:5e28e4356f6a4158426447',
    messagingSenderId: '69817314886',
    projectId: 'ems-app-74857',
    authDomain: 'ems-app-74857.firebaseapp.com',
    storageBucket: 'ems-app-74857.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr-9BOwOQYTJwccswP1bropZ5BbvHapMA',
    appId: '1:69817314886:android:452c5d6b21805ac2426447',
    messagingSenderId: '69817314886',
    projectId: 'ems-app-74857',
    storageBucket: 'ems-app-74857.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-VD6QkQj9sWlAm7UndSXkJMcq-LrOL4M',
    appId: '1:69817314886:ios:3bfd3c33f0b790d7426447',
    messagingSenderId: '69817314886',
    projectId: 'ems-app-74857',
    storageBucket: 'ems-app-74857.appspot.com',
    iosClientId: '69817314886-pmua4ug4krn0lj0a2osok7ur1lmdhli5.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-VD6QkQj9sWlAm7UndSXkJMcq-LrOL4M',
    appId: '1:69817314886:ios:3bfd3c33f0b790d7426447',
    messagingSenderId: '69817314886',
    projectId: 'ems-app-74857',
    storageBucket: 'ems-app-74857.appspot.com',
    iosClientId: '69817314886-pmua4ug4krn0lj0a2osok7ur1lmdhli5.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventApp',
  );
}
